package com.witshare.mars.pojo.vo;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class ProjectDailyInfoVo {


    private BigDecimal getEthAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_get_eth_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualGetEthAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.pay_token_amount
     *
     * @mbggenerated
     */
    private BigDecimal payTokenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_pay_token_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualPayTokenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.tx_user_count
     *
     * @mbggenerated
     */
    private Integer txUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_tx_user_count
     *
     * @mbggenerated
     */
    private Integer actualTxUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.tx_address_count
     *
     * @mbggenerated
     */
    private Integer txAddressCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_tx_address_count
     *
     * @mbggenerated
     */
    private Integer actualTxAddressCount;

    public BigDecimal getGetEthAmount() {
        return getEthAmount;
    }

    public ProjectDailyInfoVo setGetEthAmount(BigDecimal getEthAmount) {
        this.getEthAmount = getEthAmount;
        return this;
    }

    public BigDecimal getActualGetEthAmount() {
        return actualGetEthAmount;
    }

    public ProjectDailyInfoVo setActualGetEthAmount(BigDecimal actualGetEthAmount) {
        this.actualGetEthAmount = actualGetEthAmount;
        return this;
    }

    public BigDecimal getPayTokenAmount() {
        return payTokenAmount;
    }

    public ProjectDailyInfoVo setPayTokenAmount(BigDecimal payTokenAmount) {
        this.payTokenAmount = payTokenAmount;
        return this;
    }

    public BigDecimal getActualPayTokenAmount() {
        return actualPayTokenAmount;
    }

    public ProjectDailyInfoVo setActualPayTokenAmount(BigDecimal actualPayTokenAmount) {
        this.actualPayTokenAmount = actualPayTokenAmount;
        return this;
    }

    public Integer getTxUserCount() {
        return txUserCount;
    }

    public ProjectDailyInfoVo setTxUserCount(Integer txUserCount) {
        this.txUserCount = txUserCount;
        return this;
    }

    public Integer getActualTxUserCount() {
        return actualTxUserCount;
    }

    public ProjectDailyInfoVo setActualTxUserCount(Integer actualTxUserCount) {
        this.actualTxUserCount = actualTxUserCount;
        return this;
    }

    public Integer getTxAddressCount() {
        return txAddressCount;
    }

    public ProjectDailyInfoVo setTxAddressCount(Integer txAddressCount) {
        this.txAddressCount = txAddressCount;
        return this;
    }

    public Integer getActualTxAddressCount() {
        return actualTxAddressCount;
    }

    public ProjectDailyInfoVo setActualTxAddressCount(Integer actualTxAddressCount) {
        this.actualTxAddressCount = actualTxAddressCount;
        return this;
    }
}