package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class ConfBaseInfoBean {

    public static final String INFO_KEY_ZH = "infoKeyZh";
    public static final String INFO_KEY_EN = "infoKeyEn";
    public static final String PICTURE = "picture";
    public static final String INFO_VALUE_ZH = "infoValueZh";
    public static final String INFO_VALUE_EN = "infoValueEn";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.info_key_zh
     *
     * @mbg.generated
     */
    private String infoKeyZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.info_key_en
     *
     * @mbg.generated
     */
    private String infoKeyEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.picture_url
     *
     * @mbg.generated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.info_value_zh
     *
     * @mbg.generated
     */
    private String infoValueZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.info_value_en
     *
     * @mbg.generated
     */
    private String infoValueEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_base_info.update_time
     *
     * @mbg.generated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.id
     *
     * @return the value of conf_base_info.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.id
     *
     * @param id the value for conf_base_info.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.info_key_zh
     *
     * @return the value of conf_base_info.info_key_zh
     * @mbg.generated
     */
    public String getInfoKeyZh() {
        return infoKeyZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.info_key_zh
     *
     * @param infoKeyZh the value for conf_base_info.info_key_zh
     * @mbg.generated
     */
    public void setInfoKeyZh(String infoKeyZh) {
        this.infoKeyZh = infoKeyZh == null ? null : infoKeyZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.info_key_en
     *
     * @return the value of conf_base_info.info_key_en
     * @mbg.generated
     */
    public String getInfoKeyEn() {
        return infoKeyEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.info_key_en
     *
     * @param infoKeyEn the value for conf_base_info.info_key_en
     * @mbg.generated
     */
    public void setInfoKeyEn(String infoKeyEn) {
        this.infoKeyEn = infoKeyEn == null ? null : infoKeyEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.picture_url
     *
     * @return the value of conf_base_info.picture_url
     * @mbg.generated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.picture_url
     *
     * @param pictureUrl the value for conf_base_info.picture_url
     * @mbg.generated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.info_value_zh
     *
     * @return the value of conf_base_info.info_value_zh
     * @mbg.generated
     */
    public String getInfoValueZh() {
        return infoValueZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.info_value_zh
     *
     * @param infoValueZh the value for conf_base_info.info_value_zh
     * @mbg.generated
     */
    public void setInfoValueZh(String infoValueZh) {
        this.infoValueZh = infoValueZh == null ? null : infoValueZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.info_value_en
     *
     * @return the value of conf_base_info.info_value_en
     * @mbg.generated
     */
    public String getInfoValueEn() {
        return infoValueEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.info_value_en
     *
     * @param infoValueEn the value for conf_base_info.info_value_en
     * @mbg.generated
     */
    public void setInfoValueEn(String infoValueEn) {
        this.infoValueEn = infoValueEn == null ? null : infoValueEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.create_time
     *
     * @return the value of conf_base_info.create_time
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.create_time
     *
     * @param createTime the value for conf_base_info.create_time
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_base_info.update_time
     *
     * @return the value of conf_base_info.update_time
     * @mbg.generated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_base_info.update_time
     *
     * @param updateTime the value for conf_base_info.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}