package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class ConfSensitiveWordBean {
    public static final String WORD = "word";
    public static final String STATUS = "status";
    public final static int MIN_MATCH_TYPE = 1;      //最小匹配规则
    public final static int MAX_MATCH_TYPE = 2;      //最大匹配规则

    private Integer pageNum;
    private Integer pageSize;
    private String wordLike;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_sensitive_word.id
     *
     * @mbggenerated
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_sensitive_word.sensitive_word
     *
     * @mbggenerated
     */
    private String sensitiveWord;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_sensitive_word.sensitive_word_status
     *
     * @mbggenerated
     */
    private Integer sensitiveWordStatus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_sensitive_word.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_sensitive_word.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    public ConfSensitiveWordBean() {
    }

    public ConfSensitiveWordBean(String sensitiveWord, Integer sensitiveWordStatus) {
        this.sensitiveWord = sensitiveWord;
        this.sensitiveWordStatus = sensitiveWordStatus;
    }

    public Integer getPageNum() {
        return pageNum;
    }

    public void setPageNum(Integer pageNum) {
        this.pageNum = pageNum;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    public String getWordLike() {
        return wordLike;
    }

    public void setWordLike(String wordLike) {
        this.wordLike = wordLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_sensitive_word.id
     *
     * @return the value of conf_sensitive_word.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_sensitive_word.id
     *
     * @param id the value for conf_sensitive_word.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_sensitive_word.sensitive_word
     *
     * @return the value of conf_sensitive_word.sensitive_word
     * @mbggenerated
     */
    public String getSensitiveWord() {
        return sensitiveWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_sensitive_word.sensitive_word
     *
     * @param sensitiveWord the value for conf_sensitive_word.sensitive_word
     * @mbggenerated
     */
    public void setSensitiveWord(String sensitiveWord) {
        this.sensitiveWord = sensitiveWord == null ? null : sensitiveWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_sensitive_word.sensitive_word_status
     *
     * @return the value of conf_sensitive_word.sensitive_word_status
     * @mbggenerated
     */
    public Integer getSensitiveWordStatus() {
        return sensitiveWordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_sensitive_word.sensitive_word_status
     *
     * @param sensitiveWordStatus the value for conf_sensitive_word.sensitive_word_status
     * @mbggenerated
     */
    public void setSensitiveWordStatus(Integer sensitiveWordStatus) {
        this.sensitiveWordStatus = sensitiveWordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_sensitive_word.create_time
     *
     * @return the value of conf_sensitive_word.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_sensitive_word.create_time
     *
     * @param createTime the value for conf_sensitive_word.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_sensitive_word.update_time
     *
     * @return the value of conf_sensitive_word.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_sensitive_word.update_time
     *
     * @param updateTime the value for conf_sensitive_word.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}