package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class ConfProjectGradeBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_grade.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_grade.grade_name
     *
     * @mbggenerated
     */
    private String gradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_grade.grade_code
     *
     * @mbggenerated
     */
    private String gradeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_grade.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conf_project_grade.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_grade.id
     *
     * @return the value of conf_project_grade.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_grade.id
     *
     * @param id the value for conf_project_grade.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_grade.grade_name
     *
     * @return the value of conf_project_grade.grade_name
     * @mbggenerated
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_grade.grade_name
     *
     * @param gradeName the value for conf_project_grade.grade_name
     * @mbggenerated
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName == null ? null : gradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_grade.grade_code
     *
     * @return the value of conf_project_grade.grade_code
     * @mbggenerated
     */
    public String getGradeCode() {
        return gradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_grade.grade_code
     *
     * @param gradeCode the value for conf_project_grade.grade_code
     * @mbggenerated
     */
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode == null ? null : gradeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_grade.create_time
     *
     * @return the value of conf_project_grade.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_grade.create_time
     *
     * @param createTime the value for conf_project_grade.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conf_project_grade.update_time
     *
     * @return the value of conf_project_grade.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conf_project_grade.update_time
     *
     * @param updateTime the value for conf_project_grade.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}