package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class ProjectWebsiteLinkBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_website_link.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_website_link.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_website_link.link_type
     *
     * @mbggenerated
     */
    private String linkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_website_link.link_url
     *
     * @mbggenerated
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_website_link.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_website_link.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_link.id
     *
     * @return the value of project_website_link.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_link.id
     *
     * @param id the value for project_website_link.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_link.project_id
     *
     * @return the value of project_website_link.project_id
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_link.project_id
     *
     * @param projectId the value for project_website_link.project_id
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_link.link_type
     *
     * @return the value of project_website_link.link_type
     * @mbggenerated
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_link.link_type
     *
     * @param linkType the value for project_website_link.link_type
     * @mbggenerated
     */
    public void setLinkType(String linkType) {
        this.linkType = linkType == null ? null : linkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_link.link_url
     *
     * @return the value of project_website_link.link_url
     * @mbggenerated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_link.link_url
     *
     * @param linkUrl the value for project_website_link.link_url
     * @mbggenerated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_link.create_time
     *
     * @return the value of project_website_link.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_link.create_time
     *
     * @param createTime the value for project_website_link.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_link.update_time
     *
     * @return the value of project_website_link.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_link.update_time
     *
     * @param updateTime the value for project_website_link.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}