package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class ProjectAcceptingBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_accepting.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_accepting.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_accepting.accepting_id
     *
     * @mbggenerated
     */
    private Long acceptingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_accepting.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_accepting.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_accepting.id
     *
     * @return the value of project_accepting.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_accepting.id
     *
     * @param id the value for project_accepting.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_accepting.project_id
     *
     * @return the value of project_accepting.project_id
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_accepting.project_id
     *
     * @param projectId the value for project_accepting.project_id
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_accepting.accepting_id
     *
     * @return the value of project_accepting.accepting_id
     * @mbggenerated
     */
    public Long getAcceptingId() {
        return acceptingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_accepting.accepting_id
     *
     * @param acceptingId the value for project_accepting.accepting_id
     * @mbggenerated
     */
    public void setAcceptingId(Long acceptingId) {
        this.acceptingId = acceptingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_accepting.create_time
     *
     * @return the value of project_accepting.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_accepting.create_time
     *
     * @param createTime the value for project_accepting.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_accepting.update_time
     *
     * @return the value of project_accepting.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_accepting.update_time
     *
     * @param updateTime the value for project_accepting.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}