package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class ProjectWebsiteTypeBean {

    public static final String LINK_NAME = "linkName";
    public static final String PICTURE = "picture";
    public static final String ID = "id";

    private Long id;
    private Integer linkType;
    private String linkName;
    private String pictureUrl;
    private Timestamp createTime;
    private Timestamp updateTime;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_type.id
     *
     * @param id the value for project_website_type.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_type.link_type
     *
     * @return the value of project_website_type.link_type
     * @mbg.generated
     */
    public Integer getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_type.link_type
     *
     * @param linkType the value for project_website_type.link_type
     * @mbg.generated
     */
    public void setLinkType(Integer linkType) {
        this.linkType = linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_type.link_name
     *
     * @return the value of project_website_type.link_name
     * @mbg.generated
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_type.link_name
     *
     * @param linkName the value for project_website_type.link_name
     * @mbg.generated
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_type.picture_url
     *
     * @return the value of project_website_type.picture_url
     * @mbg.generated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_type.picture_url
     *
     * @param pictureUrl the value for project_website_type.picture_url
     * @mbg.generated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_type.create_time
     *
     * @return the value of project_website_type.create_time
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_type.create_time
     *
     * @param createTime the value for project_website_type.create_time
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_website_type.update_time
     *
     * @return the value of project_website_type.update_time
     * @mbg.generated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_website_type.update_time
     *
     * @param updateTime the value for project_website_type.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}