package com.witshare.mars.pojo.dto;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class ProjectDailyInfoBean {

    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.project_token
     *
     * @mbggenerated
     */
    private String projectToken;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.get_eth_amount
     *
     * @mbggenerated
     */
    private BigDecimal getEthAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_get_eth_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualGetEthAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.pay_token_amount
     *
     * @mbggenerated
     */
    private BigDecimal payTokenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_pay_token_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualPayTokenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.tx_user_count
     *
     * @mbggenerated
     */
    private Integer txUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_tx_user_count
     *
     * @mbggenerated
     */
    private Integer actualTxUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.tx_address_count
     *
     * @mbggenerated
     */
    private Integer txAddressCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_tx_address_count
     *
     * @mbggenerated
     */
    private Integer actualTxAddressCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.current_day
     *
     * @mbggenerated
     */
    private Date currentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    private ProjectDailyInfoBean() {
    }

    public static ProjectDailyInfoBean newInstance() {
        return new ProjectDailyInfoBean();
    }

    public Long getId() {
        return id;
    }

    public ProjectDailyInfoBean setId(Long id) {
        this.id = id;
        return this;
    }

    public String getProjectGid() {
        return projectGid;
    }

    public ProjectDailyInfoBean setProjectGid(String projectGid) {
        this.projectGid = projectGid;
        return this;
    }

    public String getProjectToken() {
        return projectToken;
    }

    public ProjectDailyInfoBean setProjectToken(String projectToken) {
        this.projectToken = projectToken;
        return this;
    }


    public BigDecimal getGetEthAmount() {
        return getEthAmount;
    }

    public ProjectDailyInfoBean setGetEthAmount(BigDecimal getEthAmount) {
        this.getEthAmount = getEthAmount;
        return this;
    }

    public BigDecimal getActualGetEthAmount() {
        return actualGetEthAmount;
    }

    public ProjectDailyInfoBean setActualGetEthAmount(BigDecimal actualGetEthAmount) {
        this.actualGetEthAmount = actualGetEthAmount;
        return this;
    }

    public BigDecimal getPayTokenAmount() {
        return payTokenAmount;
    }

    public ProjectDailyInfoBean setPayTokenAmount(BigDecimal payTokenAmount) {
        this.payTokenAmount = payTokenAmount;
        return this;
    }

    public BigDecimal getActualPayTokenAmount() {
        return actualPayTokenAmount;
    }

    public ProjectDailyInfoBean setActualPayTokenAmount(BigDecimal actualPayTokenAmount) {
        this.actualPayTokenAmount = actualPayTokenAmount;
        return this;
    }

    public Integer getTxUserCount() {
        return txUserCount;
    }

    public ProjectDailyInfoBean setTxUserCount(Integer txUserCount) {
        this.txUserCount = txUserCount;
        return this;
    }

    public Integer getActualTxUserCount() {
        return actualTxUserCount;
    }

    public ProjectDailyInfoBean setActualTxUserCount(Integer actualTxUserCount) {
        this.actualTxUserCount = actualTxUserCount;
        return this;
    }

    public Integer getTxAddressCount() {
        return txAddressCount;
    }

    public ProjectDailyInfoBean setTxAddressCount(Integer txAddressCount) {
        this.txAddressCount = txAddressCount;
        return this;
    }

    public Integer getActualTxAddressCount() {
        return actualTxAddressCount;
    }

    public ProjectDailyInfoBean setActualTxAddressCount(Integer actualTxAddressCount) {
        this.actualTxAddressCount = actualTxAddressCount;
        return this;
    }

    public Date getCurrentDay() {
        return currentDay;
    }

    public ProjectDailyInfoBean setCurrentDay(Date currentDay) {
        this.currentDay = currentDay;
        return this;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public ProjectDailyInfoBean setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
        return this;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public ProjectDailyInfoBean setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
        return this;
    }
}