package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class SocialSWebsiteProjectBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_website_project.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_website_project.project_id
     *
     * @mbg.generated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_website_project.social_id
     *
     * @mbg.generated
     */
    private Long socialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_website_project.link_url
     *
     * @mbg.generated
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_website_project.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_website_project.update_time
     *
     * @mbg.generated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_website_project.id
     *
     * @return the value of social_website_project.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_website_project.id
     *
     * @param id the value for social_website_project.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_website_project.project_id
     *
     * @return the value of social_website_project.project_id
     * @mbg.generated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_website_project.project_id
     *
     * @param projectId the value for social_website_project.project_id
     * @mbg.generated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_website_project.social_id
     *
     * @return the value of social_website_project.social_id
     * @mbg.generated
     */
    public Long getSocialId() {
        return socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_website_project.social_id
     *
     * @param socialId the value for social_website_project.social_id
     * @mbg.generated
     */
    public void setSocialId(Long socialId) {
        this.socialId = socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_website_project.link_url
     *
     * @return the value of social_website_project.link_url
     * @mbg.generated
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_website_project.link_url
     *
     * @param linkUrl the value for social_website_project.link_url
     * @mbg.generated
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_website_project.create_time
     *
     * @return the value of social_website_project.create_time
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_website_project.create_time
     *
     * @param createTime the value for social_website_project.create_time
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_website_project.update_time
     *
     * @return the value of social_website_project.update_time
     * @mbg.generated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_website_project.update_time
     *
     * @param updateTime the value for social_website_project.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}