package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class StaticProjectDescription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_en.project_id
     *
     * @mbg.generated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.project_instruction
     *
     * @mbggenerated
     */
    private String projectInstruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.grade_report_link
     *
     * @mbggenerated
     */
    private String gradeReportLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.project_location
     *
     * @mbggenerated
     */
    private String projectLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.white_paper_link
     *
     * @mbggenerated
     */
    private String whitePaperLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_zh.project_content
     *
     * @mbggenerated
     */
    private String projectContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.id
     *
     * @return the value of project_description_zh.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.id
     *
     * @param id the value for project_description_zh.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_en.project_id
     *
     * @return the value of project_description_en.project_id
     * @mbg.generated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_en.project_id
     *
     * @param projectId the value for project_description_en.project_id
     * @mbg.generated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.project_name
     *
     * @return the value of project_description_zh.project_name
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.project_name
     *
     * @param projectName the value for project_description_zh.project_name
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.project_instruction
     *
     * @return the value of project_description_zh.project_instruction
     * @mbggenerated
     */
    public String getProjectInstruction() {
        return projectInstruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.project_instruction
     *
     * @param projectInstruction the value for project_description_zh.project_instruction
     * @mbggenerated
     */
    public void setProjectInstruction(String projectInstruction) {
        this.projectInstruction = projectInstruction == null ? null : projectInstruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.grade_report_link
     *
     * @return the value of project_description_zh.grade_report_link
     * @mbggenerated
     */
    public String getGradeReportLink() {
        return gradeReportLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.grade_report_link
     *
     * @param gradeReportLink the value for project_description_zh.grade_report_link
     * @mbggenerated
     */
    public void setGradeReportLink(String gradeReportLink) {
        this.gradeReportLink = gradeReportLink == null ? null : gradeReportLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.project_location
     *
     * @return the value of project_description_zh.project_location
     * @mbggenerated
     */
    public String getProjectLocation() {
        return projectLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.project_location
     *
     * @param projectLocation the value for project_description_zh.project_location
     * @mbggenerated
     */
    public void setProjectLocation(String projectLocation) {
        this.projectLocation = projectLocation == null ? null : projectLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.white_paper_link
     *
     * @return the value of project_description_zh.white_paper_link
     * @mbggenerated
     */
    public String getWhitePaperLink() {
        return whitePaperLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.white_paper_link
     *
     * @param whitePaperLink the value for project_description_zh.white_paper_link
     * @mbggenerated
     */
    public void setWhitePaperLink(String whitePaperLink) {
        this.whitePaperLink = whitePaperLink == null ? null : whitePaperLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.create_time
     *
     * @return the value of project_description_zh.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.create_time
     *
     * @param createTime the value for project_description_zh.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.update_time
     *
     * @return the value of project_description_zh.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.update_time
     *
     * @param updateTime the value for project_description_zh.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_zh.project_content
     *
     * @return the value of project_description_zh.project_content
     * @mbggenerated
     */
    public String getProjectContent() {
        return projectContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_zh.project_content
     *
     * @param projectContent the value for project_description_zh.project_content
     * @mbggenerated
     */
    public void setProjectContent(String projectContent) {
        this.projectContent = projectContent == null ? null : projectContent.trim();
    }
}