package com.witshare.mars.pojo.dto;

import java.sql.Timestamp;

public class SysUserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.message_content
     *
     * @mbggenerated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.from_user_id
     *
     * @mbggenerated
     */
    private Long fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.to_user_id
     *
     * @mbggenerated
     */
    private Long toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.message_status
     *
     * @mbggenerated
     */
    private Integer messageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_message.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.id
     *
     * @return the value of sys_user_message.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.id
     *
     * @param id the value for sys_user_message.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.message_content
     *
     * @return the value of sys_user_message.message_content
     * @mbggenerated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.message_content
     *
     * @param messageContent the value for sys_user_message.message_content
     * @mbggenerated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.from_user_id
     *
     * @return the value of sys_user_message.from_user_id
     * @mbggenerated
     */
    public Long getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.from_user_id
     *
     * @param fromUserId the value for sys_user_message.from_user_id
     * @mbggenerated
     */
    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.to_user_id
     *
     * @return the value of sys_user_message.to_user_id
     * @mbggenerated
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.to_user_id
     *
     * @param toUserId the value for sys_user_message.to_user_id
     * @mbggenerated
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.message_status
     *
     * @return the value of sys_user_message.message_status
     * @mbggenerated
     */
    public Integer getMessageStatus() {
        return messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.message_status
     *
     * @param messageStatus the value for sys_user_message.message_status
     * @mbggenerated
     */
    public void setMessageStatus(Integer messageStatus) {
        this.messageStatus = messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.create_time
     *
     * @return the value of sys_user_message.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.create_time
     *
     * @param createTime the value for sys_user_message.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_message.update_time
     *
     * @return the value of sys_user_message.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_message.update_time
     *
     * @param updateTime the value for sys_user_message.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}