package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.ProjectTokenDistribution;
import com.witshare.mars.pojo.domain.ProjectTokenDistributionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectTokenDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int countByExample(ProjectTokenDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectTokenDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int insert(ProjectTokenDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int insertSelective(ProjectTokenDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    List<ProjectTokenDistribution> selectByExample(ProjectTokenDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    ProjectTokenDistribution selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectTokenDistribution record, @Param("example") ProjectTokenDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectTokenDistribution record, @Param("example") ProjectTokenDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectTokenDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_token_distribution
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectTokenDistribution record);
}