package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.ProjectDescriptionJa;
import com.witshare.mars.pojo.domain.ProjectDescriptionJaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectDescriptionJaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int countByExample(ProjectDescriptionJaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectDescriptionJaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int insert(ProjectDescriptionJa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int insertSelective(ProjectDescriptionJa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    List<ProjectDescriptionJa> selectByExampleWithBLOBs(ProjectDescriptionJaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    List<ProjectDescriptionJa> selectByExample(ProjectDescriptionJaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    ProjectDescriptionJa selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectDescriptionJa record, @Param("example") ProjectDescriptionJaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectDescriptionJa record, @Param("example") ProjectDescriptionJaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectDescriptionJa record, @Param("example") ProjectDescriptionJaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectDescriptionJa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProjectDescriptionJa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ja
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectDescriptionJa record);
}