package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.ProjectDescriptionKo;
import com.witshare.mars.pojo.domain.ProjectDescriptionKoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectDescriptionKoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int countByExample(ProjectDescriptionKoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectDescriptionKoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int insert(ProjectDescriptionKo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int insertSelective(ProjectDescriptionKo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    List<ProjectDescriptionKo> selectByExampleWithBLOBs(ProjectDescriptionKoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    List<ProjectDescriptionKo> selectByExample(ProjectDescriptionKoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    ProjectDescriptionKo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectDescriptionKo record, @Param("example") ProjectDescriptionKoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectDescriptionKo record, @Param("example") ProjectDescriptionKoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectDescriptionKo record, @Param("example") ProjectDescriptionKoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectDescriptionKo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProjectDescriptionKo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_ko
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectDescriptionKo record);
}