package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.ProjectDailyInfo;
import com.witshare.mars.pojo.domain.ProjectDailyInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectDailyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int countByExample(ProjectDailyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectDailyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int insert(ProjectDailyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int insertSelective(ProjectDailyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    List<ProjectDailyInfo> selectByExample(ProjectDailyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    ProjectDailyInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectDailyInfo record, @Param("example") ProjectDailyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectDailyInfo record, @Param("example") ProjectDailyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectDailyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectDailyInfo record);
}