package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.ProjectDescriptionCn;
import com.witshare.mars.pojo.domain.ProjectDescriptionCnExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectDescriptionCnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int countByExample(ProjectDescriptionCnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectDescriptionCnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int insert(ProjectDescriptionCn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int insertSelective(ProjectDescriptionCn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    List<ProjectDescriptionCn> selectByExampleWithBLOBs(ProjectDescriptionCnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    List<ProjectDescriptionCn> selectByExample(ProjectDescriptionCnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    ProjectDescriptionCn selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectDescriptionCn record, @Param("example") ProjectDescriptionCnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectDescriptionCn record, @Param("example") ProjectDescriptionCnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectDescriptionCn record, @Param("example") ProjectDescriptionCnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectDescriptionCn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProjectDescriptionCn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_description_cn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectDescriptionCn record);
}