package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.RecordPlatformTx;
import com.witshare.mars.pojo.domain.RecordPlatformTxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecordPlatformTxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int countByExample(RecordPlatformTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int deleteByExample(RecordPlatformTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int insert(RecordPlatformTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int insertSelective(RecordPlatformTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    List<RecordPlatformTx> selectByExample(RecordPlatformTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    RecordPlatformTx selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecordPlatformTx record, @Param("example") RecordPlatformTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecordPlatformTx record, @Param("example") RecordPlatformTxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecordPlatformTx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_platform_tx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecordPlatformTx record);
}