package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.SysProject;
import com.witshare.mars.pojo.domain.SysProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int countByExample(SysProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int deleteByExample(SysProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int insert(SysProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int insertSelective(SysProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    List<SysProject> selectByExample(SysProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    SysProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysProject record, @Param("example") SysProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysProject record, @Param("example") SysProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysProject record);
}