package com.witshare.mars.dao.mysql;

import com.witshare.mars.pojo.domain.SysUserAddress;
import com.witshare.mars.pojo.domain.SysUserAddressExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysUserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int countByExample(SysUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int deleteByExample(SysUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int insert(SysUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int insertSelective(SysUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    List<SysUserAddress> selectByExample(SysUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    SysUserAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUserAddress record, @Param("example") SysUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUserAddress record, @Param("example") SysUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserAddress record);
}