package com.witshare.mars.pojo.domain;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectDailyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public ProjectDailyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectGidIsNull() {
            addCriterion("project_gid is null");
            return (Criteria) this;
        }

        public Criteria andProjectGidIsNotNull() {
            addCriterion("project_gid is not null");
            return (Criteria) this;
        }

        public Criteria andProjectGidEqualTo(String value) {
            addCriterion("project_gid =", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotEqualTo(String value) {
            addCriterion("project_gid <>", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidGreaterThan(String value) {
            addCriterion("project_gid >", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidGreaterThanOrEqualTo(String value) {
            addCriterion("project_gid >=", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidLessThan(String value) {
            addCriterion("project_gid <", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidLessThanOrEqualTo(String value) {
            addCriterion("project_gid <=", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidLike(String value) {
            addCriterion("project_gid like", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotLike(String value) {
            addCriterion("project_gid not like", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidIn(List<String> values) {
            addCriterion("project_gid in", values, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotIn(List<String> values) {
            addCriterion("project_gid not in", values, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidBetween(String value1, String value2) {
            addCriterion("project_gid between", value1, value2, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotBetween(String value1, String value2) {
            addCriterion("project_gid not between", value1, value2, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectTokenIsNull() {
            addCriterion("project_token is null");
            return (Criteria) this;
        }

        public Criteria andProjectTokenIsNotNull() {
            addCriterion("project_token is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTokenEqualTo(String value) {
            addCriterion("project_token =", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotEqualTo(String value) {
            addCriterion("project_token <>", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenGreaterThan(String value) {
            addCriterion("project_token >", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenGreaterThanOrEqualTo(String value) {
            addCriterion("project_token >=", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenLessThan(String value) {
            addCriterion("project_token <", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenLessThanOrEqualTo(String value) {
            addCriterion("project_token <=", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenLike(String value) {
            addCriterion("project_token like", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotLike(String value) {
            addCriterion("project_token not like", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenIn(List<String> values) {
            addCriterion("project_token in", values, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotIn(List<String> values) {
            addCriterion("project_token not in", values, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenBetween(String value1, String value2) {
            addCriterion("project_token between", value1, value2, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotBetween(String value1, String value2) {
            addCriterion("project_token not between", value1, value2, "projectToken");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountIsNull() {
            addCriterion("subscription_amount is null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountIsNotNull() {
            addCriterion("subscription_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountEqualTo(BigDecimal value) {
            addCriterion("subscription_amount =", value, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountNotEqualTo(BigDecimal value) {
            addCriterion("subscription_amount <>", value, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountGreaterThan(BigDecimal value) {
            addCriterion("subscription_amount >", value, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("subscription_amount >=", value, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountLessThan(BigDecimal value) {
            addCriterion("subscription_amount <", value, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("subscription_amount <=", value, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountIn(List<BigDecimal> values) {
            addCriterion("subscription_amount in", values, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountNotIn(List<BigDecimal> values) {
            addCriterion("subscription_amount not in", values, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("subscription_amount between", value1, value2, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andSubscriptionAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("subscription_amount not between", value1, value2, "subscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountIsNull() {
            addCriterion("actual_subscription_amount is null");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountIsNotNull() {
            addCriterion("actual_subscription_amount is not null");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountEqualTo(BigDecimal value) {
            addCriterion("actual_subscription_amount =", value, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountNotEqualTo(BigDecimal value) {
            addCriterion("actual_subscription_amount <>", value, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountGreaterThan(BigDecimal value) {
            addCriterion("actual_subscription_amount >", value, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_subscription_amount >=", value, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountLessThan(BigDecimal value) {
            addCriterion("actual_subscription_amount <", value, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_subscription_amount <=", value, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountIn(List<BigDecimal> values) {
            addCriterion("actual_subscription_amount in", values, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountNotIn(List<BigDecimal> values) {
            addCriterion("actual_subscription_amount not in", values, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_subscription_amount between", value1, value2, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andActualSubscriptionAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_subscription_amount not between", value1, value2, "actualSubscriptionAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountIsNull() {
            addCriterion("distribute_amount is null");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountIsNotNull() {
            addCriterion("distribute_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountEqualTo(BigDecimal value) {
            addCriterion("distribute_amount =", value, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountNotEqualTo(BigDecimal value) {
            addCriterion("distribute_amount <>", value, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountGreaterThan(BigDecimal value) {
            addCriterion("distribute_amount >", value, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("distribute_amount >=", value, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountLessThan(BigDecimal value) {
            addCriterion("distribute_amount <", value, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("distribute_amount <=", value, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountIn(List<BigDecimal> values) {
            addCriterion("distribute_amount in", values, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountNotIn(List<BigDecimal> values) {
            addCriterion("distribute_amount not in", values, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("distribute_amount between", value1, value2, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andDistributeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("distribute_amount not between", value1, value2, "distributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountIsNull() {
            addCriterion("actual_distribute_amount is null");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountIsNotNull() {
            addCriterion("actual_distribute_amount is not null");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountEqualTo(BigDecimal value) {
            addCriterion("actual_distribute_amount =", value, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountNotEqualTo(BigDecimal value) {
            addCriterion("actual_distribute_amount <>", value, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountGreaterThan(BigDecimal value) {
            addCriterion("actual_distribute_amount >", value, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_distribute_amount >=", value, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountLessThan(BigDecimal value) {
            addCriterion("actual_distribute_amount <", value, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_distribute_amount <=", value, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountIn(List<BigDecimal> values) {
            addCriterion("actual_distribute_amount in", values, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountNotIn(List<BigDecimal> values) {
            addCriterion("actual_distribute_amount not in", values, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_distribute_amount between", value1, value2, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andActualDistributeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_distribute_amount not between", value1, value2, "actualDistributeAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountIsNull() {
            addCriterion("tx_user_amount is null");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountIsNotNull() {
            addCriterion("tx_user_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountEqualTo(BigDecimal value) {
            addCriterion("tx_user_amount =", value, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountNotEqualTo(BigDecimal value) {
            addCriterion("tx_user_amount <>", value, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountGreaterThan(BigDecimal value) {
            addCriterion("tx_user_amount >", value, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tx_user_amount >=", value, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountLessThan(BigDecimal value) {
            addCriterion("tx_user_amount <", value, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tx_user_amount <=", value, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountIn(List<BigDecimal> values) {
            addCriterion("tx_user_amount in", values, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountNotIn(List<BigDecimal> values) {
            addCriterion("tx_user_amount not in", values, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tx_user_amount between", value1, value2, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tx_user_amount not between", value1, value2, "txUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountIsNull() {
            addCriterion("actual_tx_user_amount is null");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountIsNotNull() {
            addCriterion("actual_tx_user_amount is not null");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountEqualTo(BigDecimal value) {
            addCriterion("actual_tx_user_amount =", value, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountNotEqualTo(BigDecimal value) {
            addCriterion("actual_tx_user_amount <>", value, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountGreaterThan(BigDecimal value) {
            addCriterion("actual_tx_user_amount >", value, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_tx_user_amount >=", value, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountLessThan(BigDecimal value) {
            addCriterion("actual_tx_user_amount <", value, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_tx_user_amount <=", value, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountIn(List<BigDecimal> values) {
            addCriterion("actual_tx_user_amount in", values, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountNotIn(List<BigDecimal> values) {
            addCriterion("actual_tx_user_amount not in", values, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_tx_user_amount between", value1, value2, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_tx_user_amount not between", value1, value2, "actualTxUserAmount");
            return (Criteria) this;
        }

        public Criteria andCurrentDayIsNull() {
            addCriterion("current_day is null");
            return (Criteria) this;
        }

        public Criteria andCurrentDayIsNotNull() {
            addCriterion("current_day is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentDayEqualTo(Date value) {
            addCriterionForJDBCDate("current_day =", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayNotEqualTo(Date value) {
            addCriterionForJDBCDate("current_day <>", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayGreaterThan(Date value) {
            addCriterionForJDBCDate("current_day >", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("current_day >=", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayLessThan(Date value) {
            addCriterionForJDBCDate("current_day <", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("current_day <=", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayIn(List<Date> values) {
            addCriterionForJDBCDate("current_day in", values, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayNotIn(List<Date> values) {
            addCriterionForJDBCDate("current_day not in", values, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("current_day between", value1, value2, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("current_day not between", value1, value2, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Timestamp value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Timestamp value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Timestamp value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Timestamp> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_daily_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}