package com.witshare.mars.pojo.domain;

import java.sql.Timestamp;

public class ProjectDescriptionKo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.project_instruction
     *
     * @mbggenerated
     */
    private String projectInstruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.grade_report_link
     *
     * @mbggenerated
     */
    private String gradeReportLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.white_paper_link
     *
     * @mbggenerated
     */
    private String whitePaperLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_description_ko.project_content
     *
     * @mbggenerated
     */
    private String projectContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.id
     *
     * @return the value of project_description_ko.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.id
     *
     * @param id the value for project_description_ko.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.project_gid
     *
     * @return the value of project_description_ko.project_gid
     * @mbggenerated
     */
    public String getProjectGid() {
        return projectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.project_gid
     *
     * @param projectGid the value for project_description_ko.project_gid
     * @mbggenerated
     */
    public void setProjectGid(String projectGid) {
        this.projectGid = projectGid == null ? null : projectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.project_name
     *
     * @return the value of project_description_ko.project_name
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.project_name
     *
     * @param projectName the value for project_description_ko.project_name
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.project_instruction
     *
     * @return the value of project_description_ko.project_instruction
     * @mbggenerated
     */
    public String getProjectInstruction() {
        return projectInstruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.project_instruction
     *
     * @param projectInstruction the value for project_description_ko.project_instruction
     * @mbggenerated
     */
    public void setProjectInstruction(String projectInstruction) {
        this.projectInstruction = projectInstruction == null ? null : projectInstruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.grade_report_link
     *
     * @return the value of project_description_ko.grade_report_link
     * @mbggenerated
     */
    public String getGradeReportLink() {
        return gradeReportLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.grade_report_link
     *
     * @param gradeReportLink the value for project_description_ko.grade_report_link
     * @mbggenerated
     */
    public void setGradeReportLink(String gradeReportLink) {
        this.gradeReportLink = gradeReportLink == null ? null : gradeReportLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.white_paper_link
     *
     * @return the value of project_description_ko.white_paper_link
     * @mbggenerated
     */
    public String getWhitePaperLink() {
        return whitePaperLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.white_paper_link
     *
     * @param whitePaperLink the value for project_description_ko.white_paper_link
     * @mbggenerated
     */
    public void setWhitePaperLink(String whitePaperLink) {
        this.whitePaperLink = whitePaperLink == null ? null : whitePaperLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.create_time
     *
     * @return the value of project_description_ko.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.create_time
     *
     * @param createTime the value for project_description_ko.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.update_time
     *
     * @return the value of project_description_ko.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.update_time
     *
     * @param updateTime the value for project_description_ko.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_description_ko.project_content
     *
     * @return the value of project_description_ko.project_content
     * @mbggenerated
     */
    public String getProjectContent() {
        return projectContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_description_ko.project_content
     *
     * @param projectContent the value for project_description_ko.project_content
     * @mbggenerated
     */
    public void setProjectContent(String projectContent) {
        this.projectContent = projectContent == null ? null : projectContent.trim();
    }
}