package com.witshare.mars.pojo.domain;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class ProjectDailyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.project_token
     *
     * @mbggenerated
     */
    private String projectToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.price_rate
     *
     * @mbggenerated
     */
    private BigDecimal priceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.get_eth_amount
     *
     * @mbggenerated
     */
    private BigDecimal getEthAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_get_eth_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualGetEthAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.pay_token_amount
     *
     * @mbggenerated
     */
    private BigDecimal payTokenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_pay_token_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualPayTokenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.tx_user_count
     *
     * @mbggenerated
     */
    private Integer txUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_tx_user_count
     *
     * @mbggenerated
     */
    private Integer actualTxUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.tx_address_count
     *
     * @mbggenerated
     */
    private Integer txAddressCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_tx_address_count
     *
     * @mbggenerated
     */
    private Integer actualTxAddressCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.current_day
     *
     * @mbggenerated
     */
    private Date currentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.id
     *
     * @return the value of project_daily_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.id
     *
     * @param id the value for project_daily_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.project_gid
     *
     * @return the value of project_daily_info.project_gid
     *
     * @mbggenerated
     */
    public String getProjectGid() {
        return projectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.project_gid
     *
     * @param projectGid the value for project_daily_info.project_gid
     *
     * @mbggenerated
     */
    public void setProjectGid(String projectGid) {
        this.projectGid = projectGid == null ? null : projectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.project_token
     *
     * @return the value of project_daily_info.project_token
     *
     * @mbggenerated
     */
    public String getProjectToken() {
        return projectToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.project_token
     *
     * @param projectToken the value for project_daily_info.project_token
     *
     * @mbggenerated
     */
    public void setProjectToken(String projectToken) {
        this.projectToken = projectToken == null ? null : projectToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.price_rate
     *
     * @return the value of project_daily_info.price_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPriceRate() {
        return priceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.price_rate
     *
     * @param priceRate the value for project_daily_info.price_rate
     *
     * @mbggenerated
     */
    public void setPriceRate(BigDecimal priceRate) {
        this.priceRate = priceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.get_eth_amount
     *
     * @return the value of project_daily_info.get_eth_amount
     *
     * @mbggenerated
     */
    public BigDecimal getGetEthAmount() {
        return getEthAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.get_eth_amount
     *
     * @param getEthAmount the value for project_daily_info.get_eth_amount
     *
     * @mbggenerated
     */
    public void setGetEthAmount(BigDecimal getEthAmount) {
        this.getEthAmount = getEthAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.actual_get_eth_amount
     *
     * @return the value of project_daily_info.actual_get_eth_amount
     *
     * @mbggenerated
     */
    public BigDecimal getActualGetEthAmount() {
        return actualGetEthAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.actual_get_eth_amount
     *
     * @param actualGetEthAmount the value for project_daily_info.actual_get_eth_amount
     *
     * @mbggenerated
     */
    public void setActualGetEthAmount(BigDecimal actualGetEthAmount) {
        this.actualGetEthAmount = actualGetEthAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.pay_token_amount
     *
     * @return the value of project_daily_info.pay_token_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPayTokenAmount() {
        return payTokenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.pay_token_amount
     *
     * @param payTokenAmount the value for project_daily_info.pay_token_amount
     *
     * @mbggenerated
     */
    public void setPayTokenAmount(BigDecimal payTokenAmount) {
        this.payTokenAmount = payTokenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.actual_pay_token_amount
     *
     * @return the value of project_daily_info.actual_pay_token_amount
     *
     * @mbggenerated
     */
    public BigDecimal getActualPayTokenAmount() {
        return actualPayTokenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.actual_pay_token_amount
     *
     * @param actualPayTokenAmount the value for project_daily_info.actual_pay_token_amount
     *
     * @mbggenerated
     */
    public void setActualPayTokenAmount(BigDecimal actualPayTokenAmount) {
        this.actualPayTokenAmount = actualPayTokenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.tx_user_count
     *
     * @return the value of project_daily_info.tx_user_count
     *
     * @mbggenerated
     */
    public Integer getTxUserCount() {
        return txUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.tx_user_count
     *
     * @param txUserCount the value for project_daily_info.tx_user_count
     *
     * @mbggenerated
     */
    public void setTxUserCount(Integer txUserCount) {
        this.txUserCount = txUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.actual_tx_user_count
     *
     * @return the value of project_daily_info.actual_tx_user_count
     *
     * @mbggenerated
     */
    public Integer getActualTxUserCount() {
        return actualTxUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.actual_tx_user_count
     *
     * @param actualTxUserCount the value for project_daily_info.actual_tx_user_count
     *
     * @mbggenerated
     */
    public void setActualTxUserCount(Integer actualTxUserCount) {
        this.actualTxUserCount = actualTxUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.tx_address_count
     *
     * @return the value of project_daily_info.tx_address_count
     * @mbggenerated
     */
    public Integer getTxAddressCount() {
        return txAddressCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.tx_address_count
     *
     * @param txAddressCount the value for project_daily_info.tx_address_count
     * @mbggenerated
     */
    public void setTxAddressCount(Integer txAddressCount) {
        this.txAddressCount = txAddressCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.actual_tx_address_count
     *
     * @return the value of project_daily_info.actual_tx_address_count
     * @mbggenerated
     */
    public Integer getActualTxAddressCount() {
        return actualTxAddressCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.actual_tx_address_count
     *
     * @param actualTxAddressCount the value for project_daily_info.actual_tx_address_count
     * @mbggenerated
     */
    public void setActualTxAddressCount(Integer actualTxAddressCount) {
        this.actualTxAddressCount = actualTxAddressCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.current_day
     *
     * @return the value of project_daily_info.current_day
     *
     * @mbggenerated
     */
    public Date getCurrentDay() {
        return currentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.current_day
     *
     * @param currentDay the value for project_daily_info.current_day
     *
     * @mbggenerated
     */
    public void setCurrentDay(Date currentDay) {
        this.currentDay = currentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.create_time
     *
     * @return the value of project_daily_info.create_time
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.create_time
     *
     * @param createTime the value for project_daily_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.update_time
     *
     * @return the value of project_daily_info.update_time
     *
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.update_time
     *
     * @param updateTime the value for project_daily_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}