package com.witshare.mars.pojo.domain;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectDailyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public ProjectDailyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectGidIsNull() {
            addCriterion("project_gid is null");
            return (Criteria) this;
        }

        public Criteria andProjectGidIsNotNull() {
            addCriterion("project_gid is not null");
            return (Criteria) this;
        }

        public Criteria andProjectGidEqualTo(String value) {
            addCriterion("project_gid =", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotEqualTo(String value) {
            addCriterion("project_gid <>", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidGreaterThan(String value) {
            addCriterion("project_gid >", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidGreaterThanOrEqualTo(String value) {
            addCriterion("project_gid >=", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidLessThan(String value) {
            addCriterion("project_gid <", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidLessThanOrEqualTo(String value) {
            addCriterion("project_gid <=", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidLike(String value) {
            addCriterion("project_gid like", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotLike(String value) {
            addCriterion("project_gid not like", value, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidIn(List<String> values) {
            addCriterion("project_gid in", values, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotIn(List<String> values) {
            addCriterion("project_gid not in", values, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidBetween(String value1, String value2) {
            addCriterion("project_gid between", value1, value2, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectGidNotBetween(String value1, String value2) {
            addCriterion("project_gid not between", value1, value2, "projectGid");
            return (Criteria) this;
        }

        public Criteria andProjectTokenIsNull() {
            addCriterion("project_token is null");
            return (Criteria) this;
        }

        public Criteria andProjectTokenIsNotNull() {
            addCriterion("project_token is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTokenEqualTo(String value) {
            addCriterion("project_token =", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotEqualTo(String value) {
            addCriterion("project_token <>", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenGreaterThan(String value) {
            addCriterion("project_token >", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenGreaterThanOrEqualTo(String value) {
            addCriterion("project_token >=", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenLessThan(String value) {
            addCriterion("project_token <", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenLessThanOrEqualTo(String value) {
            addCriterion("project_token <=", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenLike(String value) {
            addCriterion("project_token like", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotLike(String value) {
            addCriterion("project_token not like", value, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenIn(List<String> values) {
            addCriterion("project_token in", values, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotIn(List<String> values) {
            addCriterion("project_token not in", values, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenBetween(String value1, String value2) {
            addCriterion("project_token between", value1, value2, "projectToken");
            return (Criteria) this;
        }

        public Criteria andProjectTokenNotBetween(String value1, String value2) {
            addCriterion("project_token not between", value1, value2, "projectToken");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountIsNull() {
            addCriterion("get_eth_amount is null");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountIsNotNull() {
            addCriterion("get_eth_amount is not null");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountEqualTo(BigDecimal value) {
            addCriterion("get_eth_amount =", value, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountNotEqualTo(BigDecimal value) {
            addCriterion("get_eth_amount <>", value, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountGreaterThan(BigDecimal value) {
            addCriterion("get_eth_amount >", value, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("get_eth_amount >=", value, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountLessThan(BigDecimal value) {
            addCriterion("get_eth_amount <", value, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("get_eth_amount <=", value, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountIn(List<BigDecimal> values) {
            addCriterion("get_eth_amount in", values, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountNotIn(List<BigDecimal> values) {
            addCriterion("get_eth_amount not in", values, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("get_eth_amount between", value1, value2, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andGetEthAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("get_eth_amount not between", value1, value2, "getEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountIsNull() {
            addCriterion("actual_get_eth_amount is null");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountIsNotNull() {
            addCriterion("actual_get_eth_amount is not null");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountEqualTo(BigDecimal value) {
            addCriterion("actual_get_eth_amount =", value, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountNotEqualTo(BigDecimal value) {
            addCriterion("actual_get_eth_amount <>", value, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountGreaterThan(BigDecimal value) {
            addCriterion("actual_get_eth_amount >", value, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_get_eth_amount >=", value, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountLessThan(BigDecimal value) {
            addCriterion("actual_get_eth_amount <", value, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_get_eth_amount <=", value, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountIn(List<BigDecimal> values) {
            addCriterion("actual_get_eth_amount in", values, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountNotIn(List<BigDecimal> values) {
            addCriterion("actual_get_eth_amount not in", values, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_get_eth_amount between", value1, value2, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andActualGetEthAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_get_eth_amount not between", value1, value2, "actualGetEthAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountIsNull() {
            addCriterion("pay_token_amount is null");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountIsNotNull() {
            addCriterion("pay_token_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountEqualTo(BigDecimal value) {
            addCriterion("pay_token_amount =", value, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountNotEqualTo(BigDecimal value) {
            addCriterion("pay_token_amount <>", value, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountGreaterThan(BigDecimal value) {
            addCriterion("pay_token_amount >", value, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_token_amount >=", value, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountLessThan(BigDecimal value) {
            addCriterion("pay_token_amount <", value, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_token_amount <=", value, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountIn(List<BigDecimal> values) {
            addCriterion("pay_token_amount in", values, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountNotIn(List<BigDecimal> values) {
            addCriterion("pay_token_amount not in", values, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_token_amount between", value1, value2, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andPayTokenAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_token_amount not between", value1, value2, "payTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountIsNull() {
            addCriterion("actual_pay_token_amount is null");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountIsNotNull() {
            addCriterion("actual_pay_token_amount is not null");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountEqualTo(BigDecimal value) {
            addCriterion("actual_pay_token_amount =", value, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountNotEqualTo(BigDecimal value) {
            addCriterion("actual_pay_token_amount <>", value, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountGreaterThan(BigDecimal value) {
            addCriterion("actual_pay_token_amount >", value, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_pay_token_amount >=", value, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountLessThan(BigDecimal value) {
            addCriterion("actual_pay_token_amount <", value, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("actual_pay_token_amount <=", value, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountIn(List<BigDecimal> values) {
            addCriterion("actual_pay_token_amount in", values, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountNotIn(List<BigDecimal> values) {
            addCriterion("actual_pay_token_amount not in", values, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_pay_token_amount between", value1, value2, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andActualPayTokenAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("actual_pay_token_amount not between", value1, value2, "actualPayTokenAmount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountIsNull() {
            addCriterion("tx_user_count is null");
            return (Criteria) this;
        }

        public Criteria andTxUserCountIsNotNull() {
            addCriterion("tx_user_count is not null");
            return (Criteria) this;
        }

        public Criteria andTxUserCountEqualTo(Integer value) {
            addCriterion("tx_user_count =", value, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountNotEqualTo(Integer value) {
            addCriterion("tx_user_count <>", value, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountGreaterThan(Integer value) {
            addCriterion("tx_user_count >", value, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("tx_user_count >=", value, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountLessThan(Integer value) {
            addCriterion("tx_user_count <", value, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountLessThanOrEqualTo(Integer value) {
            addCriterion("tx_user_count <=", value, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountIn(List<Integer> values) {
            addCriterion("tx_user_count in", values, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountNotIn(List<Integer> values) {
            addCriterion("tx_user_count not in", values, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountBetween(Integer value1, Integer value2) {
            addCriterion("tx_user_count between", value1, value2, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andTxUserCountNotBetween(Integer value1, Integer value2) {
            addCriterion("tx_user_count not between", value1, value2, "txUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountIsNull() {
            addCriterion("actual_tx_user_count is null");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountIsNotNull() {
            addCriterion("actual_tx_user_count is not null");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountEqualTo(Integer value) {
            addCriterion("actual_tx_user_count =", value, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountNotEqualTo(Integer value) {
            addCriterion("actual_tx_user_count <>", value, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountGreaterThan(Integer value) {
            addCriterion("actual_tx_user_count >", value, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("actual_tx_user_count >=", value, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountLessThan(Integer value) {
            addCriterion("actual_tx_user_count <", value, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountLessThanOrEqualTo(Integer value) {
            addCriterion("actual_tx_user_count <=", value, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountIn(List<Integer> values) {
            addCriterion("actual_tx_user_count in", values, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountNotIn(List<Integer> values) {
            addCriterion("actual_tx_user_count not in", values, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountBetween(Integer value1, Integer value2) {
            addCriterion("actual_tx_user_count between", value1, value2, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andActualTxUserCountNotBetween(Integer value1, Integer value2) {
            addCriterion("actual_tx_user_count not between", value1, value2, "actualTxUserCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountIsNull() {
            addCriterion("tx_address_count is null");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountIsNotNull() {
            addCriterion("tx_address_count is not null");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountEqualTo(Integer value) {
            addCriterion("tx_address_count =", value, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountNotEqualTo(Integer value) {
            addCriterion("tx_address_count <>", value, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountGreaterThan(Integer value) {
            addCriterion("tx_address_count >", value, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("tx_address_count >=", value, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountLessThan(Integer value) {
            addCriterion("tx_address_count <", value, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountLessThanOrEqualTo(Integer value) {
            addCriterion("tx_address_count <=", value, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountIn(List<Integer> values) {
            addCriterion("tx_address_count in", values, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountNotIn(List<Integer> values) {
            addCriterion("tx_address_count not in", values, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountBetween(Integer value1, Integer value2) {
            addCriterion("tx_address_count between", value1, value2, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andTxAddressCountNotBetween(Integer value1, Integer value2) {
            addCriterion("tx_address_count not between", value1, value2, "txAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountIsNull() {
            addCriterion("actual_tx_address_count is null");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountIsNotNull() {
            addCriterion("actual_tx_address_count is not null");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountEqualTo(Integer value) {
            addCriterion("actual_tx_address_count =", value, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountNotEqualTo(Integer value) {
            addCriterion("actual_tx_address_count <>", value, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountGreaterThan(Integer value) {
            addCriterion("actual_tx_address_count >", value, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("actual_tx_address_count >=", value, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountLessThan(Integer value) {
            addCriterion("actual_tx_address_count <", value, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountLessThanOrEqualTo(Integer value) {
            addCriterion("actual_tx_address_count <=", value, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountIn(List<Integer> values) {
            addCriterion("actual_tx_address_count in", values, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountNotIn(List<Integer> values) {
            addCriterion("actual_tx_address_count not in", values, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountBetween(Integer value1, Integer value2) {
            addCriterion("actual_tx_address_count between", value1, value2, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andActualTxAddressCountNotBetween(Integer value1, Integer value2) {
            addCriterion("actual_tx_address_count not between", value1, value2, "actualTxAddressCount");
            return (Criteria) this;
        }

        public Criteria andCurrentDayIsNull() {
            addCriterion("current_day is null");
            return (Criteria) this;
        }

        public Criteria andCurrentDayIsNotNull() {
            addCriterion("current_day is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentDayEqualTo(Date value) {
            addCriterionForJDBCDate("current_day =", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayNotEqualTo(Date value) {
            addCriterionForJDBCDate("current_day <>", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayGreaterThan(Date value) {
            addCriterionForJDBCDate("current_day >", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("current_day >=", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayLessThan(Date value) {
            addCriterionForJDBCDate("current_day <", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("current_day <=", value, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayIn(List<Date> values) {
            addCriterionForJDBCDate("current_day in", values, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayNotIn(List<Date> values) {
            addCriterionForJDBCDate("current_day not in", values, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("current_day between", value1, value2, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCurrentDayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("current_day not between", value1, value2, "currentDay");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Timestamp value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Timestamp value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Timestamp value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Timestamp> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_daily_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_daily_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}