package com.witshare.mars.pojo.domain;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class ProjectDailyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.project_token
     *
     * @mbggenerated
     */
    private String projectToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.subscription_amount
     *
     * @mbggenerated
     */
    private BigDecimal subscriptionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_subscription_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualSubscriptionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.distribute_amount
     *
     * @mbggenerated
     */
    private BigDecimal distributeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_distribute_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualDistributeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.tx_user_amount
     *
     * @mbggenerated
     */
    private BigDecimal txUserAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.actual_tx_user_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualTxUserAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.current_day
     *
     * @mbggenerated
     */
    private Date currentDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_daily_info.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.id
     *
     * @return the value of project_daily_info.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.id
     *
     * @param id the value for project_daily_info.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.project_gid
     *
     * @return the value of project_daily_info.project_gid
     * @mbggenerated
     */
    public String getProjectGid() {
        return projectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.project_gid
     *
     * @param projectGid the value for project_daily_info.project_gid
     * @mbggenerated
     */
    public void setProjectGid(String projectGid) {
        this.projectGid = projectGid == null ? null : projectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.project_token
     *
     * @return the value of project_daily_info.project_token
     * @mbggenerated
     */
    public String getProjectToken() {
        return projectToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.project_token
     *
     * @param projectToken the value for project_daily_info.project_token
     * @mbggenerated
     */
    public void setProjectToken(String projectToken) {
        this.projectToken = projectToken == null ? null : projectToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.price
     *
     * @return the value of project_daily_info.price
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.price
     *
     * @param price the value for project_daily_info.price
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.subscription_amount
     *
     * @return the value of project_daily_info.subscription_amount
     * @mbggenerated
     */
    public BigDecimal getSubscriptionAmount() {
        return subscriptionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.subscription_amount
     *
     * @param subscriptionAmount the value for project_daily_info.subscription_amount
     * @mbggenerated
     */
    public void setSubscriptionAmount(BigDecimal subscriptionAmount) {
        this.subscriptionAmount = subscriptionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.actual_subscription_amount
     *
     * @return the value of project_daily_info.actual_subscription_amount
     * @mbggenerated
     */
    public BigDecimal getActualSubscriptionAmount() {
        return actualSubscriptionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.actual_subscription_amount
     *
     * @param actualSubscriptionAmount the value for project_daily_info.actual_subscription_amount
     * @mbggenerated
     */
    public void setActualSubscriptionAmount(BigDecimal actualSubscriptionAmount) {
        this.actualSubscriptionAmount = actualSubscriptionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.distribute_amount
     *
     * @return the value of project_daily_info.distribute_amount
     * @mbggenerated
     */
    public BigDecimal getDistributeAmount() {
        return distributeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.distribute_amount
     *
     * @param distributeAmount the value for project_daily_info.distribute_amount
     * @mbggenerated
     */
    public void setDistributeAmount(BigDecimal distributeAmount) {
        this.distributeAmount = distributeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.actual_distribute_amount
     *
     * @return the value of project_daily_info.actual_distribute_amount
     * @mbggenerated
     */
    public BigDecimal getActualDistributeAmount() {
        return actualDistributeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.actual_distribute_amount
     *
     * @param actualDistributeAmount the value for project_daily_info.actual_distribute_amount
     * @mbggenerated
     */
    public void setActualDistributeAmount(BigDecimal actualDistributeAmount) {
        this.actualDistributeAmount = actualDistributeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.tx_user_amount
     *
     * @return the value of project_daily_info.tx_user_amount
     * @mbggenerated
     */
    public BigDecimal getTxUserAmount() {
        return txUserAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.tx_user_amount
     *
     * @param txUserAmount the value for project_daily_info.tx_user_amount
     * @mbggenerated
     */
    public void setTxUserAmount(BigDecimal txUserAmount) {
        this.txUserAmount = txUserAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.actual_tx_user_amount
     *
     * @return the value of project_daily_info.actual_tx_user_amount
     * @mbggenerated
     */
    public BigDecimal getActualTxUserAmount() {
        return actualTxUserAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.actual_tx_user_amount
     *
     * @param actualTxUserAmount the value for project_daily_info.actual_tx_user_amount
     * @mbggenerated
     */
    public void setActualTxUserAmount(BigDecimal actualTxUserAmount) {
        this.actualTxUserAmount = actualTxUserAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.current_day
     *
     * @return the value of project_daily_info.current_day
     * @mbggenerated
     */
    public Date getCurrentDay() {
        return currentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.current_day
     *
     * @param currentDay the value for project_daily_info.current_day
     * @mbggenerated
     */
    public void setCurrentDay(Date currentDay) {
        this.currentDay = currentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.create_time
     *
     * @return the value of project_daily_info.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.create_time
     *
     * @param createTime the value for project_daily_info.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_daily_info.update_time
     *
     * @return the value of project_daily_info.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_daily_info.update_time
     *
     * @param updateTime the value for project_daily_info.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}