package com.witshare.mars.pojo.domain;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class ProjectTokenDistribution {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_token_distribution.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_token_distribution.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_token_distribution.project_token
     *
     * @mbggenerated
     */
    private String projectToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_token_distribution.distribute_object
     *
     * @mbggenerated
     */
    private String distributeObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_token_distribution.distribute_percent
     *
     * @mbggenerated
     */
    private BigDecimal distributePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_token_distribution.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_token_distribution.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_token_distribution.id
     *
     * @return the value of project_token_distribution.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_token_distribution.id
     *
     * @param id the value for project_token_distribution.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_token_distribution.project_gid
     *
     * @return the value of project_token_distribution.project_gid
     * @mbggenerated
     */
    public String getProjectGid() {
        return projectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_token_distribution.project_gid
     *
     * @param projectGid the value for project_token_distribution.project_gid
     * @mbggenerated
     */
    public void setProjectGid(String projectGid) {
        this.projectGid = projectGid == null ? null : projectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_token_distribution.project_token
     *
     * @return the value of project_token_distribution.project_token
     * @mbggenerated
     */
    public String getProjectToken() {
        return projectToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_token_distribution.project_token
     *
     * @param projectToken the value for project_token_distribution.project_token
     * @mbggenerated
     */
    public void setProjectToken(String projectToken) {
        this.projectToken = projectToken == null ? null : projectToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_token_distribution.distribute_object
     *
     * @return the value of project_token_distribution.distribute_object
     * @mbggenerated
     */
    public String getDistributeObject() {
        return distributeObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_token_distribution.distribute_object
     *
     * @param distributeObject the value for project_token_distribution.distribute_object
     * @mbggenerated
     */
    public void setDistributeObject(String distributeObject) {
        this.distributeObject = distributeObject == null ? null : distributeObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_token_distribution.distribute_percent
     *
     * @return the value of project_token_distribution.distribute_percent
     * @mbggenerated
     */
    public BigDecimal getDistributePercent() {
        return distributePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_token_distribution.distribute_percent
     *
     * @param distributePercent the value for project_token_distribution.distribute_percent
     * @mbggenerated
     */
    public void setDistributePercent(BigDecimal distributePercent) {
        this.distributePercent = distributePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_token_distribution.create_time
     *
     * @return the value of project_token_distribution.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_token_distribution.create_time
     *
     * @param createTime the value for project_token_distribution.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_token_distribution.update_time
     *
     * @return the value of project_token_distribution.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_token_distribution.update_time
     *
     * @param updateTime the value for project_token_distribution.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}