package com.witshare.mars.pojo.domain;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class RecordPlatformTx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.tx_hash
     *
     * @mbggenerated
     */
    private String txHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.tx_type
     *
     * @mbggenerated
     */
    private int txType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.from_name
     *
     * @mbggenerated
     */
    private String fromName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.from_address
     *
     * @mbggenerated
     */
    private String fromAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.to_name
     *
     * @mbggenerated
     */
    private String toName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.to_address
     *
     * @mbggenerated
     */
    private String toAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.tx_token_type
     *
     * @mbggenerated
     */
    private String txTokenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.tx_amount
     *
     * @mbggenerated
     */
    private String txAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.eth_fee
     *
     * @mbggenerated
     */
    private BigDecimal ethFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_platform_tx.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.id
     *
     * @return the value of record_platform_tx.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.id
     *
     * @param id the value for record_platform_tx.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.project_gid
     *
     * @return the value of record_platform_tx.project_gid
     * @mbggenerated
     */
    public String getProjectGid() {
        return projectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.project_gid
     *
     * @param projectGid the value for record_platform_tx.project_gid
     * @mbggenerated
     */
    public void setProjectGid(String projectGid) {
        this.projectGid = projectGid == null ? null : projectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.tx_hash
     *
     * @return the value of record_platform_tx.tx_hash
     * @mbggenerated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.tx_hash
     *
     * @param txHash the value for record_platform_tx.tx_hash
     * @mbggenerated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.tx_type
     *
     * @return the value of record_platform_tx.tx_type
     * @mbggenerated
     */
    public int getTxType() {
        return txType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.tx_type
     *
     * @param txType the value for record_platform_tx.tx_type
     * @mbggenerated
     */
    public void setTxType(int txType) {
        this.txType = txType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.from_name
     *
     * @return the value of record_platform_tx.from_name
     * @mbggenerated
     */
    public String getFromName() {
        return fromName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.from_name
     *
     * @param fromName the value for record_platform_tx.from_name
     * @mbggenerated
     */
    public void setFromName(String fromName) {
        this.fromName = fromName == null ? null : fromName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.from_address
     *
     * @return the value of record_platform_tx.from_address
     * @mbggenerated
     */
    public String getFromAddress() {
        return fromAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.from_address
     *
     * @param fromAddress the value for record_platform_tx.from_address
     * @mbggenerated
     */
    public void setFromAddress(String fromAddress) {
        this.fromAddress = fromAddress == null ? null : fromAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.to_name
     *
     * @return the value of record_platform_tx.to_name
     * @mbggenerated
     */
    public String getToName() {
        return toName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.to_name
     *
     * @param toName the value for record_platform_tx.to_name
     * @mbggenerated
     */
    public void setToName(String toName) {
        this.toName = toName == null ? null : toName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.to_address
     *
     * @return the value of record_platform_tx.to_address
     * @mbggenerated
     */
    public String getToAddress() {
        return toAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.to_address
     *
     * @param toAddress the value for record_platform_tx.to_address
     * @mbggenerated
     */
    public void setToAddress(String toAddress) {
        this.toAddress = toAddress == null ? null : toAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.tx_token_type
     *
     * @return the value of record_platform_tx.tx_token_type
     * @mbggenerated
     */
    public String getTxTokenType() {
        return txTokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.tx_token_type
     *
     * @param txTokenType the value for record_platform_tx.tx_token_type
     * @mbggenerated
     */
    public void setTxTokenType(String txTokenType) {
        this.txTokenType = txTokenType == null ? null : txTokenType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.tx_amount
     *
     * @return the value of record_platform_tx.tx_amount
     * @mbggenerated
     */
    public String getTxAmount() {
        return txAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.tx_amount
     *
     * @param txAmount the value for record_platform_tx.tx_amount
     * @mbggenerated
     */
    public void setTxAmount(String txAmount) {
        this.txAmount = txAmount == null ? null : txAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.eth_fee
     *
     * @return the value of record_platform_tx.eth_fee
     * @mbggenerated
     */
    public BigDecimal getEthFee() {
        return ethFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.eth_fee
     *
     * @param ethFee the value for record_platform_tx.eth_fee
     * @mbggenerated
     */
    public void setEthFee(BigDecimal ethFee) {
        this.ethFee = ethFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.create_time
     *
     * @return the value of record_platform_tx.create_time
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.create_time
     *
     * @param createTime the value for record_platform_tx.create_time
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_platform_tx.update_time
     *
     * @return the value of record_platform_tx.update_time
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_platform_tx.update_time
     *
     * @param updateTime the value for record_platform_tx.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}