package com.witshare.mars.pojo.domain;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class SysProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.project_token
     *
     * @mbggenerated
     */
    private String projectToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.token_address
     *
     * @mbggenerated
     */
    private String tokenAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.platform_address
     *
     * @mbggenerated
     */
    private String platformAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.project_address
     *
     * @mbggenerated
     */
    private String projectAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.project_logo_link
     *
     * @mbggenerated
     */
    private String projectLogoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.project_img_link
     *
     * @mbggenerated
     */
    private String projectImgLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.soft_cap
     *
     * @mbggenerated
     */
    private BigDecimal softCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.hard_cap
     *
     * @mbggenerated
     */
    private BigDecimal hardCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.min_purchase_amount
     *
     * @mbggenerated
     */
    private BigDecimal minPurchaseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.start_time
     *
     * @mbggenerated
     */
    private Timestamp startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.end_time
     *
     * @mbggenerated
     */
    private Timestamp endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.start_price_rate
     *
     * @mbggenerated
     */
    private BigDecimal startPriceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.end_price_rate
     *
     * @mbggenerated
     */
    private BigDecimal endPriceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.project_status
     *
     * @mbggenerated
     */
    private int projectStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.is_available
     *
     * @mbggenerated
     */
    private int isAvailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_project.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.id
     *
     * @return the value of sys_project.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.id
     *
     * @param id the value for sys_project.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.project_gid
     *
     * @return the value of sys_project.project_gid
     *
     * @mbggenerated
     */
    public String getProjectGid() {
        return projectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.project_gid
     *
     * @param projectGid the value for sys_project.project_gid
     *
     * @mbggenerated
     */
    public void setProjectGid(String projectGid) {
        this.projectGid = projectGid == null ? null : projectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.project_token
     *
     * @return the value of sys_project.project_token
     *
     * @mbggenerated
     */
    public String getProjectToken() {
        return projectToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.project_token
     *
     * @param projectToken the value for sys_project.project_token
     *
     * @mbggenerated
     */
    public void setProjectToken(String projectToken) {
        this.projectToken = projectToken == null ? null : projectToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.token_address
     *
     * @return the value of sys_project.token_address
     *
     * @mbggenerated
     */
    public String getTokenAddress() {
        return tokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.token_address
     *
     * @param tokenAddress the value for sys_project.token_address
     *
     * @mbggenerated
     */
    public void setTokenAddress(String tokenAddress) {
        this.tokenAddress = tokenAddress == null ? null : tokenAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.platform_address
     *
     * @return the value of sys_project.platform_address
     *
     * @mbggenerated
     */
    public String getPlatformAddress() {
        return platformAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.platform_address
     *
     * @param platformAddress the value for sys_project.platform_address
     *
     * @mbggenerated
     */
    public void setPlatformAddress(String platformAddress) {
        this.platformAddress = platformAddress == null ? null : platformAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.project_address
     *
     * @return the value of sys_project.project_address
     *
     * @mbggenerated
     */
    public String getProjectAddress() {
        return projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.project_address
     *
     * @param projectAddress the value for sys_project.project_address
     *
     * @mbggenerated
     */
    public void setProjectAddress(String projectAddress) {
        this.projectAddress = projectAddress == null ? null : projectAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.project_logo_link
     *
     * @return the value of sys_project.project_logo_link
     *
     * @mbggenerated
     */
    public String getProjectLogoLink() {
        return projectLogoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.project_logo_link
     *
     * @param projectLogoLink the value for sys_project.project_logo_link
     *
     * @mbggenerated
     */
    public void setProjectLogoLink(String projectLogoLink) {
        this.projectLogoLink = projectLogoLink == null ? null : projectLogoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.project_img_link
     *
     * @return the value of sys_project.project_img_link
     *
     * @mbggenerated
     */
    public String getProjectImgLink() {
        return projectImgLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.project_img_link
     *
     * @param projectImgLink the value for sys_project.project_img_link
     *
     * @mbggenerated
     */
    public void setProjectImgLink(String projectImgLink) {
        this.projectImgLink = projectImgLink == null ? null : projectImgLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.soft_cap
     *
     * @return the value of sys_project.soft_cap
     *
     * @mbggenerated
     */
    public BigDecimal getSoftCap() {
        return softCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.soft_cap
     *
     * @param softCap the value for sys_project.soft_cap
     *
     * @mbggenerated
     */
    public void setSoftCap(BigDecimal softCap) {
        this.softCap = softCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.hard_cap
     *
     * @return the value of sys_project.hard_cap
     *
     * @mbggenerated
     */
    public BigDecimal getHardCap() {
        return hardCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.hard_cap
     *
     * @param hardCap the value for sys_project.hard_cap
     *
     * @mbggenerated
     */
    public void setHardCap(BigDecimal hardCap) {
        this.hardCap = hardCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.min_purchase_amount
     *
     * @return the value of sys_project.min_purchase_amount
     *
     * @mbggenerated
     */
    public BigDecimal getMinPurchaseAmount() {
        return minPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.min_purchase_amount
     *
     * @param minPurchaseAmount the value for sys_project.min_purchase_amount
     *
     * @mbggenerated
     */
    public void setMinPurchaseAmount(BigDecimal minPurchaseAmount) {
        this.minPurchaseAmount = minPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.start_time
     *
     * @return the value of sys_project.start_time
     *
     * @mbggenerated
     */
    public Timestamp getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.start_time
     *
     * @param startTime the value for sys_project.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.end_time
     *
     * @return the value of sys_project.end_time
     *
     * @mbggenerated
     */
    public Timestamp getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.end_time
     *
     * @param endTime the value for sys_project.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.start_price_rate
     *
     * @return the value of sys_project.start_price_rate
     *
     * @mbggenerated
     */
    public BigDecimal getStartPriceRate() {
        return startPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.start_price_rate
     *
     * @param startPriceRate the value for sys_project.start_price_rate
     *
     * @mbggenerated
     */
    public void setStartPriceRate(BigDecimal startPriceRate) {
        this.startPriceRate = startPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.end_price_rate
     *
     * @return the value of sys_project.end_price_rate
     *
     * @mbggenerated
     */
    public BigDecimal getEndPriceRate() {
        return endPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.end_price_rate
     *
     * @param endPriceRate the value for sys_project.end_price_rate
     *
     * @mbggenerated
     */
    public void setEndPriceRate(BigDecimal endPriceRate) {
        this.endPriceRate = endPriceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.project_status
     *
     * @return the value of sys_project.project_status
     *
     * @mbggenerated
     */
    public int getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.project_status
     *
     * @param projectStatus the value for sys_project.project_status
     *
     * @mbggenerated
     */
    public void setProjectStatus(int projectStatus) {
        this.projectStatus = projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.is_available
     *
     * @return the value of sys_project.is_available
     *
     * @mbggenerated
     */
    public int getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.is_available
     *
     * @param isAvailable the value for sys_project.is_available
     *
     * @mbggenerated
     */
    public void setIsAvailable(int isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.create_time
     *
     * @return the value of sys_project.create_time
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.create_time
     *
     * @param createTime the value for sys_project.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_project.update_time
     *
     * @return the value of sys_project.update_time
     *
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_project.update_time
     *
     * @param updateTime the value for sys_project.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}