package com.witshare.mars.pojo.domain;

import java.sql.Timestamp;

public class SysUserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.user_gid
     *
     * @mbggenerated
     */
    private String userGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.project_gid
     *
     * @mbggenerated
     */
    private String projectGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.project_token
     *
     * @mbggenerated
     */
    private String projectToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.pay_eth_address
     *
     * @mbggenerated
     */
    private String payEthAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.get_token_address
     *
     * @mbggenerated
     */
    private String getTokenAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.create_time
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_address.update_time
     *
     * @mbggenerated
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.id
     *
     * @return the value of sys_user_address.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.id
     *
     * @param id the value for sys_user_address.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.user_gid
     *
     * @return the value of sys_user_address.user_gid
     *
     * @mbggenerated
     */
    public String getUserGid() {
        return userGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.user_gid
     *
     * @param userGid the value for sys_user_address.user_gid
     *
     * @mbggenerated
     */
    public void setUserGid(String userGid) {
        this.userGid = userGid == null ? null : userGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.email
     *
     * @return the value of sys_user_address.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.email
     *
     * @param email the value for sys_user_address.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.project_gid
     *
     * @return the value of sys_user_address.project_gid
     *
     * @mbggenerated
     */
    public String getProjectGid() {
        return projectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.project_gid
     *
     * @param projectGid the value for sys_user_address.project_gid
     *
     * @mbggenerated
     */
    public void setProjectGid(String projectGid) {
        this.projectGid = projectGid == null ? null : projectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.project_token
     *
     * @return the value of sys_user_address.project_token
     *
     * @mbggenerated
     */
    public String getProjectToken() {
        return projectToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.project_token
     *
     * @param projectToken the value for sys_user_address.project_token
     *
     * @mbggenerated
     */
    public void setProjectToken(String projectToken) {
        this.projectToken = projectToken == null ? null : projectToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.pay_eth_address
     *
     * @return the value of sys_user_address.pay_eth_address
     *
     * @mbggenerated
     */
    public String getPayEthAddress() {
        return payEthAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.pay_eth_address
     *
     * @param payEthAddress the value for sys_user_address.pay_eth_address
     *
     * @mbggenerated
     */
    public void setPayEthAddress(String payEthAddress) {
        this.payEthAddress = payEthAddress == null ? null : payEthAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.get_token_address
     *
     * @return the value of sys_user_address.get_token_address
     *
     * @mbggenerated
     */
    public String getGetTokenAddress() {
        return getTokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.get_token_address
     *
     * @param getTokenAddress the value for sys_user_address.get_token_address
     *
     * @mbggenerated
     */
    public void setGetTokenAddress(String getTokenAddress) {
        this.getTokenAddress = getTokenAddress == null ? null : getTokenAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.create_time
     *
     * @return the value of sys_user_address.create_time
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.create_time
     *
     * @param createTime the value for sys_user_address.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_address.update_time
     *
     * @return the value of sys_user_address.update_time
     *
     * @mbggenerated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_address.update_time
     *
     * @param updateTime the value for sys_user_address.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}